services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nuvvi-frontend-local
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8002:80"
    networks:
      - nuvvi-network

networks:
  nuvvi-network:
    driver: bridge
